print('########################################')
print('#         ALGORITMOS EM PYTHON         #')
print('########################################')
print('# Escolha a opção desejada:            #')
print('#                                      #')
print('# 1. Fibonacci                         #')
print('########################################')
